{"fullName": "testCases.test_login.TestLogin#test_login_00_failure", "historyId": "8d3fdf7e5ff3089f76dfc1d6b59c68b3", "labels": [{"name": "story", "value": "异常登录测试"}, {"name": "feature", "value": "测试登录功能"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "suite", "value": "test_login"}, {"name": "parentSuite", "value": "testCases"}, {"name": "host", "value": "DESKTOP-6IIPB06"}, {"name": "thread", "value": "8932-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}], "parameters": [{"name": "invalid_datas", "value": "{'pwd': 'admin@123456', 'username': 'admin111', 'exp': '登录失败'}"}], "status": "passed", "name": "test_login_00_failure[invalid_datas0]", "start": 1630548591917, "attachments": [{"type": "text/plain", "source": "f825b6a2-2f56-4fcd-a95d-33ec2d6e66e8-attachment.txt", "name": "log"}], "stop": 1630548592257, "testCaseId": "2560b1f5fa20bb64c3ef64234187c151", "uuid": "a35de157-af3f-443d-acac-11fbb896416a"}